"""add_mfa_fields_to_user

Revision ID: 4e9a571a07e6
Revises: 60428494cb5d
Create Date: 2025-12-21 20:03:31.778231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e9a571a07e6'
down_revision: Union[str, Sequence[str], None] = '60428494cb5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mfa_secret', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('is_mfa_enabled', sa.Boolean(), nullable=False, server_default=sa.text('false')))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_mfa_enabled')
        batch_op.drop_column('mfa_secret')

    # ### end Alembic commands ###
