"""add title to coin

Revision ID: 5a981e30d080
Revises: 4e9a571a07e6
Create Date: 2025-12-23 23:10:41.307354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a981e30d080'
down_revision: Union[str, Sequence[str], None] = '4e9a571a07e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=False, server_default=''))
        batch_op.create_index(batch_op.f('ix_coins_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coins_title'))
        batch_op.drop_column('title')

    # ### end Alembic commands ###
