"""add_is_admin_to_user_and_create_audit_log_table

Revision ID: 5ba353257a31
Revises: 93e54cc0b811
Create Date: 2025-12-21 11:50:12.761288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ba353257a31'
down_revision: Union[str, Sequence[str], None] = '93e54cc0b811'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coinauditlogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coin_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'IMPORT', 'ADJUST_IN', 'ADJUST_OUT', name='auditlogaction'), nullable=False),
    sa.Column('delta_quantity', sa.Integer(), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_email', sa.String(length=320), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_coinauditlogs_actor_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['coin_id'], ['coins.id'], name=op.f('fk_coinauditlogs_coin_id_coins'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coinauditlogs'))
    )
    with op.batch_alter_table('coinauditlogs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coinauditlogs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_coinauditlogs_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coinauditlogs_coin_id'), ['coin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coinauditlogs_id'), ['id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_admin', existing_type=sa.Boolean(), nullable=True)
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('coinauditlogs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coinauditlogs_id'))
        batch_op.drop_index(batch_op.f('ix_coinauditlogs_coin_id'))
        batch_op.drop_index(batch_op.f('ix_coinauditlogs_actor_user_id'))
        batch_op.drop_index(batch_op.f('ix_coinauditlogs_action'))

    op.drop_table('coinauditlogs')
    # ### end Alembic commands ###
