"""add quantity to coin

Revision ID: 93e54cc0b811
Revises: 3647e399b1cc
Create Date: 2025-12-19 00:00:43.646223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93e54cc0b811'
down_revision: Union[str, Sequence[str], None] = '3647e399b1cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coins', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
